needsNumberFolder:
  - One Piece
  - Boruto - Naruto Next Generations
seasons:
  Shingeki no Kyojin: 4
  Boku no Hero Academia: 6
changeName:
  'Shingeki no Kyojin (The Final Season)': Shingeki no Kyojin
