needsNumberFolder:
  - One Piece
  - Boruto - Naruto Next Generations
seasons:
  Shingeki no Kyojin: 4
  Boku no Hero Academia: 6
  Spy x Family: 2
  Mob Psycho 100: 3
  Jujutsu Kaisen: 2
changeName:
  'Shingeki no Kyojin (The Final Season)': 'Shingeki no Kyojin'
  'Mob Psycho 100 S3': 'Mob Psycho 100' 
