'Mob Psycho 100':
  season: 3

'One Piece':
  season: 1
  needsNumberFolder: true

'Boruto - Naruto Next Generations'
  season: 1
  needsNumberFolder: true

'Boku no Hero Academia':
  season: 6

'Spy x Family':
  season: 3

'Jujutsu Kaisen':
  season: 2
